services:
  postgres:
    image: 'postgres:18'
    environment:
      - 'POSTGRES_DB=local'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: